site_name: BERTopic
repo_url: https://github.com/MaartenGr/BERTopic
site_url: https://maartengr.github.io/BERTopic/
site_description: Leveraging BERT and a class-based TF-IDF to create easily interpretable topics.
site_author: Maarten P. Grootendorst
use_directory_urls: false
extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - The Algorithm: algorithm/algorithm.md
  - Getting Started:
      - getting_started/quickstart/quickstart.md
      - Embedding Models: getting_started/embeddings/embeddings.md
      - Topic Visualization: getting_started/visualization/visualization.md
      - Topic Reduction: getting_started/topicreduction/topicreduction.md
      - Topic Representation: getting_started/topicrepresentation/topicrepresentation.md
      - Search Topics: getting_started/search/search.md
      - Customization:
        - Custom Embedding Models: getting_started/custom_embeddings/embeddings.md
        - Custom Sub-Models: getting_started/models/models.md
        - Parameter tuning: getting_started/parameter tuning/parametertuning.md
      - Variations:
        - Topics per Class: getting_started/topicsperclass/topicsperclass.md
        - (semi)-Supervised Topic Modeling: getting_started/supervised/supervised.md
        - Dynamic Topic Modeling: getting_started/topicsovertime/topicsovertime.md
        - Guided Topic Modeling: getting_started/guided/guided.md
  - FAQ: faq.md
  - API:
      - BERTopic: api/bertopic.md
      - cTFIDF: api/ctfidf.md
      - MMR: api/mmr.md
      - Backends:
        - Base: api/backends/base.md
        - Word Doc: api/backends/word_doc.md
      - Plotting:
        - Barchart: api/plotting/barchart.md
        - Distribution: api/plotting/distribution.md
        - Heatmap: api/plotting/heatmap.md
        - Hierarchy: api/plotting/hierarchy.md
        - Term Scores: api/plotting/term.md
        - Topics: api/plotting/topics.md
        - DTM: api/plotting/dtm.md
        - Topics per Class: api/plotting/topics_per_class.md
  - Changelog: changelog.md
plugins:
  - mkdocstrings:
      watch:
        - bertopic
  - search
copyright: Copyright &copy; 2021 Maintained by <a href="https://github.com/MaartenGr">Maarten</a>.
theme:
  custom_dir: images/
  name: material
  icon:
    logo: material/library
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: icon.png
  logo: icon_white.png
  feature:
    tabs: true
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
  palette: # 

    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate # 

      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

